# Botanical details for every weed class the model can predict.
# Keys must match the folder / class names used in training.

def w(sci, fam, order, cat, native, notes):
    return {"scientific": sci, "family": fam, "order": order,
            "category": cat, "native": native, "notes": notes}

WEED_INFO = {
    # ---------- DeepWeeds (rangeland weeds) ----------
    "Chinee apple": w("Ziziphus mauritiana", "Rhamnaceae", "Rosales",
        "Broadleaf (dicot) · perennial woody shrub / small tree", "South & Southeast Asia",
        "Known as 'ber' in India, where it is a fruit tree; a declared invasive weed in Australia."),
    "Lantana": w("Lantana camara", "Verbenaceae", "Lamiales",
        "Broadleaf (dicot) · perennial shrub", "Tropical Americas",
        "One of the world's worst invasive weeds; widespread in Indian forests and toxic to cattle."),
    "Parkinsonia": w("Parkinsonia aculeata", "Fabaceae", "Fabales",
        "Broadleaf (dicot) · perennial thorny shrub / small tree", "Tropical Americas",
        "Forms dense thickets along waterways and wetlands."),
    "Parthenium": w("Parthenium hysterophorus", "Asteraceae", "Asterales",
        "Broadleaf (dicot) · annual herb", "Tropical Americas",
        "'Congress grass' in India. Causes dermatitis and asthma; reduces crop and pasture yield."),
    "Prickly acacia": w("Vachellia nilotica (syn. Acacia nilotica)", "Fabaceae", "Fabales",
        "Broadleaf (dicot) · perennial thorny tree", "Africa and Indian subcontinent",
        "'Babul' in India; a major invasive weed of grasslands in Australia."),
    "Rubber vine": w("Cryptostegia grandiflora", "Apocynaceae", "Gentianales",
        "Broadleaf (dicot) · perennial woody climber", "Madagascar",
        "Smothers riverside trees; milky sap is poisonous to livestock and people."),
    "Siam weed": w("Chromolaena odorata", "Asteraceae", "Asterales",
        "Broadleaf (dicot) · perennial scrambling shrub", "Tropical Americas",
        "Highly invasive in the Western Ghats and Northeast India; fire hazard, toxic to livestock."),
    "Snake weed": w("Stachytarpheta spp.", "Verbenaceae", "Lamiales",
        "Broadleaf (dicot) · perennial herb / sub-shrub", "Tropical Americas",
        "Invades pastures, roadsides and disturbed land."),

    # ---------- CottonWeedID15 (field crop weeds) ----------
    "Carpetweed": w("Mollugo verticillata", "Molluginaceae", "Caryophyllales",
        "Broadleaf (dicot) · annual, mat-forming", "Tropical Americas",
        "Low mat-forming weed of row crops and gardens."),
    "Crabgrass": w("Digitaria sanguinalis", "Poaceae", "Poales",
        "Grass (monocot) · annual", "Europe and Asia",
        "Fast-spreading grass weed of crops, lawns and gardens."),
    "Eclipta": w("Eclipta prostrata", "Asteraceae", "Asterales",
        "Broadleaf (dicot) · annual herb", "Tropical and subtropical regions worldwide",
        "'Bhringraj' in India; a common weed of rice and moist fields."),
    "Goosegrass": w("Eleusine indica", "Poaceae", "Poales",
        "Grass (monocot) · annual", "Tropical Asia and Africa",
        "Tough, herbicide-resistant grass weed common across Indian fields."),
    "Morningglory": w("Ipomoea spp.", "Convolvulaceae", "Solanales",
        "Broadleaf (dicot) · annual twining vine", "Tropical Americas",
        "Twines around crop plants and interferes with harvesting."),
    "Nutsedge": w("Cyperus spp. (C. rotundus / C. esculentus)", "Cyperaceae", "Poales",
        "Sedge (monocot) · perennial with tubers", "Worldwide (tropics and warm temperate)",
        "'Motha' in India; spreads by underground tubers and is among the world's worst weeds."),
    "Palmer amaranth": w("Amaranthus palmeri", "Amaranthaceae", "Caryophyllales",
        "Broadleaf (dicot) · annual", "Southwestern USA and Mexico",
        "Very fast-growing; many populations resist herbicides."),
    "Prickly sida": w("Sida spinosa", "Malvaceae", "Malvales",
        "Broadleaf (dicot) · annual", "Tropical regions",
        "Common weed of cotton, soybean and other row crops."),
    "Purslane": w("Portulaca oleracea", "Portulacaceae", "Caryophyllales",
        "Broadleaf (dicot) · annual succulent", "Uncertain; widespread worldwide",
        "Succulent weed that re-roots from stem pieces; also eaten as a vegetable ('kulfa')."),
    "Ragweed": w("Ambrosia artemisiifolia", "Asteraceae", "Asterales",
        "Broadleaf (dicot) · annual", "North America",
        "Its pollen is a major cause of hay fever."),
    "Sicklepod": w("Senna obtusifolia", "Fabaceae", "Fabales",
        "Broadleaf (dicot) · annual legume", "Tropical Americas",
        "Competes strongly with soybean, cotton and peanut."),
    "Spotted spurge": w("Euphorbia maculata", "Euphorbiaceae", "Malpighiales",
        "Broadleaf (dicot) · annual, prostrate", "North America",
        "Low-growing weed with irritating milky sap."),
    "Spurred anoda": w("Anoda cristata", "Malvaceae", "Malvales",
        "Broadleaf (dicot) · annual", "Mexico and Central/South America",
        "Weed of cotton and other summer crops."),
    "Swinecress": w("Lepidium didymum (syn. Coronopus didymus)", "Brassicaceae", "Brassicales",
        "Broadleaf (dicot) · annual / biennial", "South America",
        "Common weed of winter crops and lawns; taints milk when eaten by cattle."),
    "Waterhemp": w("Amaranthus tuberculatus", "Amaranthaceae", "Caryophyllales",
        "Broadleaf (dicot) · annual", "North America",
        "Prolific seed producer with widespread herbicide resistance."),

    # ---------- Plant Seedlings (Aarhus) ----------
    "Black-grass": w("Alopecurus myosuroides", "Poaceae", "Poales",
        "Grass (monocot) · annual", "Europe and Western Asia",
        "Serious weed of winter wheat; often herbicide-resistant."),
    "Charlock": w("Sinapis arvensis", "Brassicaceae", "Brassicales",
        "Broadleaf (dicot) · annual", "Mediterranean, Europe and Asia",
        "Wild mustard; competes with cereals and oilseed crops."),
    "Cleavers": w("Galium aparine", "Rubiaceae", "Gentianales",
        "Broadleaf (dicot) · annual scrambling climber", "Europe, Asia and North Africa",
        "Sticky hooked stems climb over crops and cause lodging."),
    "Common chickweed": w("Stellaria media", "Caryophyllaceae", "Caryophyllales",
        "Broadleaf (dicot) · annual", "Europe",
        "Forms dense mats in cool-season crops and gardens."),
    "Fat hen": w("Chenopodium album", "Amaranthaceae", "Caryophyllales",
        "Broadleaf (dicot) · annual", "Europe and Asia",
        "'Bathua' in India; a common weed of wheat and winter crops."),
    "Loose silky-bent": w("Apera spica-venti", "Poaceae", "Poales",
        "Grass (monocot) · annual", "Europe and Asia",
        "Grass weed of winter cereals."),
    "Scentless mayweed": w("Tripleurospermum inodorum", "Asteraceae", "Asterales",
        "Broadleaf (dicot) · annual / biennial", "Europe",
        "Daisy-like weed of cereals and oilseed rape."),
    "Shepherds purse": w("Capsella bursa-pastoris", "Brassicaceae", "Brassicales",
        "Broadleaf (dicot) · annual", "Eastern Europe and Asia Minor",
        "Named for its heart-shaped seed pods; very common worldwide."),
    "Small-flowered cranesbill": w("Geranium pusillum", "Geraniaceae", "Geraniales",
        "Broadleaf (dicot) · annual", "Europe and Western Asia",
        "Weed of arable land and grassland."),

    # ---------- Early Crop Weed ----------
    "Black nightshade": w("Solanum nigrum", "Solanaceae", "Solanales",
        "Broadleaf (dicot) · annual", "Eurasia",
        "'Makoi' in India. Unripe berries and leaves can be toxic."),
    "Velvetleaf": w("Abutilon theophrasti", "Malvaceae", "Malvales",
        "Broadleaf (dicot) · annual", "Southern Asia",
        "Velvety leaves; a major weed of maize, soybean and cotton."),
}
